################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../libavfilter/af_aconvert.o \
../libavfilter/af_aformat.o \
../libavfilter/af_amerge.o \
../libavfilter/af_amix.o \
../libavfilter/af_anull.o \
../libavfilter/af_aresample.o \
../libavfilter/af_ashowinfo.o \
../libavfilter/af_astreamsync.o \
../libavfilter/af_earwax.o \
../libavfilter/af_pan.o \
../libavfilter/af_silencedetect.o \
../libavfilter/af_volume.o \
../libavfilter/allfilters.o \
../libavfilter/asink_anullsink.o \
../libavfilter/asrc_aevalsrc.o \
../libavfilter/asrc_anullsrc.o \
../libavfilter/audio.o \
../libavfilter/avcodec.o \
../libavfilter/avfilter.o \
../libavfilter/avfiltergraph.o \
../libavfilter/bbox.o \
../libavfilter/buffer.o \
../libavfilter/buffersink.o \
../libavfilter/buffersrc.o \
../libavfilter/defaults.o \
../libavfilter/drawutils.o \
../libavfilter/formats.o \
../libavfilter/graphdump.o \
../libavfilter/graphparser.o \
../libavfilter/lavfutils.o \
../libavfilter/lswsutils.o \
../libavfilter/sink_buffer.o \
../libavfilter/split.o \
../libavfilter/src_buffer.o \
../libavfilter/src_movie.o \
../libavfilter/transform.o \
../libavfilter/vf_aspect.o \
../libavfilter/vf_bbox.o \
../libavfilter/vf_blackdetect.o \
../libavfilter/vf_blackframe.o \
../libavfilter/vf_boxblur.o \
../libavfilter/vf_colormatrix.o \
../libavfilter/vf_copy.o \
../libavfilter/vf_crop.o \
../libavfilter/vf_cropdetect.o \
../libavfilter/vf_delogo.o \
../libavfilter/vf_deshake.o \
../libavfilter/vf_drawbox.o \
../libavfilter/vf_fade.o \
../libavfilter/vf_fieldorder.o \
../libavfilter/vf_fifo.o \
../libavfilter/vf_format.o \
../libavfilter/vf_fps.o \
../libavfilter/vf_gradfun.o \
../libavfilter/vf_hflip.o \
../libavfilter/vf_hqdn3d.o \
../libavfilter/vf_idet.o \
../libavfilter/vf_lut.o \
../libavfilter/vf_mp.o \
../libavfilter/vf_null.o \
../libavfilter/vf_overlay.o \
../libavfilter/vf_pad.o \
../libavfilter/vf_pixdesctest.o \
../libavfilter/vf_removelogo.o \
../libavfilter/vf_scale.o \
../libavfilter/vf_select.o \
../libavfilter/vf_setfield.o \
../libavfilter/vf_setpts.o \
../libavfilter/vf_settb.o \
../libavfilter/vf_showinfo.o \
../libavfilter/vf_slicify.o \
../libavfilter/vf_super2xsai.o \
../libavfilter/vf_swapuv.o \
../libavfilter/vf_thumbnail.o \
../libavfilter/vf_tile.o \
../libavfilter/vf_tinterlace.o \
../libavfilter/vf_transpose.o \
../libavfilter/vf_unsharp.o \
../libavfilter/vf_vflip.o \
../libavfilter/vf_yadif.o \
../libavfilter/video.o \
../libavfilter/vsink_nullsink.o \
../libavfilter/vsrc_cellauto.o \
../libavfilter/vsrc_color.o \
../libavfilter/vsrc_life.o \
../libavfilter/vsrc_mandelbrot.o \
../libavfilter/vsrc_mptestsrc.o \
../libavfilter/vsrc_testsrc.o 

C_SRCS += \
../libavfilter/af_aconvert.c \
../libavfilter/af_aformat.c \
../libavfilter/af_amerge.c \
../libavfilter/af_amix.c \
../libavfilter/af_anull.c \
../libavfilter/af_aresample.c \
../libavfilter/af_ashowinfo.c \
../libavfilter/af_astreamsync.c \
../libavfilter/af_asyncts.c \
../libavfilter/af_earwax.c \
../libavfilter/af_pan.c \
../libavfilter/af_resample.c \
../libavfilter/af_silencedetect.c \
../libavfilter/af_volume.c \
../libavfilter/allfilters.c \
../libavfilter/asink_anullsink.c \
../libavfilter/asrc_aevalsrc.c \
../libavfilter/asrc_anullsrc.c \
../libavfilter/audio.c \
../libavfilter/avcodec.c \
../libavfilter/avfilter.c \
../libavfilter/avfiltergraph.c \
../libavfilter/bbox.c \
../libavfilter/buffer.c \
../libavfilter/buffersink.c \
../libavfilter/buffersrc.c \
../libavfilter/defaults.c \
../libavfilter/drawutils.c \
../libavfilter/formats.c \
../libavfilter/graphdump.c \
../libavfilter/graphparser.c \
../libavfilter/lavfutils.c \
../libavfilter/lswsutils.c \
../libavfilter/sink_buffer.c \
../libavfilter/split.c \
../libavfilter/src_buffer.c \
../libavfilter/src_movie.c \
../libavfilter/transform.c \
../libavfilter/vf_aspect.c \
../libavfilter/vf_ass.c \
../libavfilter/vf_bbox.c \
../libavfilter/vf_blackdetect.c \
../libavfilter/vf_blackframe.c \
../libavfilter/vf_boxblur.c \
../libavfilter/vf_colormatrix.c \
../libavfilter/vf_copy.c \
../libavfilter/vf_crop.c \
../libavfilter/vf_cropdetect.c \
../libavfilter/vf_delogo.c \
../libavfilter/vf_deshake.c \
../libavfilter/vf_drawbox.c \
../libavfilter/vf_drawtext.c \
../libavfilter/vf_fade.c \
../libavfilter/vf_fieldorder.c \
../libavfilter/vf_fifo.c \
../libavfilter/vf_format.c \
../libavfilter/vf_fps.c \
../libavfilter/vf_frei0r.c \
../libavfilter/vf_gradfun.c \
../libavfilter/vf_hflip.c \
../libavfilter/vf_hqdn3d.c \
../libavfilter/vf_idet.c \
../libavfilter/vf_libopencv.c \
../libavfilter/vf_lut.c \
../libavfilter/vf_mp.c \
../libavfilter/vf_null.c \
../libavfilter/vf_overlay.c \
../libavfilter/vf_pad.c \
../libavfilter/vf_pixdesctest.c \
../libavfilter/vf_removelogo.c \
../libavfilter/vf_scale.c \
../libavfilter/vf_select.c \
../libavfilter/vf_setfield.c \
../libavfilter/vf_setpts.c \
../libavfilter/vf_settb.c \
../libavfilter/vf_showinfo.c \
../libavfilter/vf_slicify.c \
../libavfilter/vf_super2xsai.c \
../libavfilter/vf_swapuv.c \
../libavfilter/vf_thumbnail.c \
../libavfilter/vf_tile.c \
../libavfilter/vf_tinterlace.c \
../libavfilter/vf_transpose.c \
../libavfilter/vf_unsharp.c \
../libavfilter/vf_vflip.c \
../libavfilter/vf_yadif.c \
../libavfilter/video.c \
../libavfilter/vsink_nullsink.c \
../libavfilter/vsrc_cellauto.c \
../libavfilter/vsrc_color.c \
../libavfilter/vsrc_life.c \
../libavfilter/vsrc_mandelbrot.c \
../libavfilter/vsrc_mptestsrc.c \
../libavfilter/vsrc_testsrc.c 

OBJS += \
./libavfilter/af_aconvert.o \
./libavfilter/af_aformat.o \
./libavfilter/af_amerge.o \
./libavfilter/af_amix.o \
./libavfilter/af_anull.o \
./libavfilter/af_aresample.o \
./libavfilter/af_ashowinfo.o \
./libavfilter/af_astreamsync.o \
./libavfilter/af_asyncts.o \
./libavfilter/af_earwax.o \
./libavfilter/af_pan.o \
./libavfilter/af_resample.o \
./libavfilter/af_silencedetect.o \
./libavfilter/af_volume.o \
./libavfilter/allfilters.o \
./libavfilter/asink_anullsink.o \
./libavfilter/asrc_aevalsrc.o \
./libavfilter/asrc_anullsrc.o \
./libavfilter/audio.o \
./libavfilter/avcodec.o \
./libavfilter/avfilter.o \
./libavfilter/avfiltergraph.o \
./libavfilter/bbox.o \
./libavfilter/buffer.o \
./libavfilter/buffersink.o \
./libavfilter/buffersrc.o \
./libavfilter/defaults.o \
./libavfilter/drawutils.o \
./libavfilter/formats.o \
./libavfilter/graphdump.o \
./libavfilter/graphparser.o \
./libavfilter/lavfutils.o \
./libavfilter/lswsutils.o \
./libavfilter/sink_buffer.o \
./libavfilter/split.o \
./libavfilter/src_buffer.o \
./libavfilter/src_movie.o \
./libavfilter/transform.o \
./libavfilter/vf_aspect.o \
./libavfilter/vf_ass.o \
./libavfilter/vf_bbox.o \
./libavfilter/vf_blackdetect.o \
./libavfilter/vf_blackframe.o \
./libavfilter/vf_boxblur.o \
./libavfilter/vf_colormatrix.o \
./libavfilter/vf_copy.o \
./libavfilter/vf_crop.o \
./libavfilter/vf_cropdetect.o \
./libavfilter/vf_delogo.o \
./libavfilter/vf_deshake.o \
./libavfilter/vf_drawbox.o \
./libavfilter/vf_drawtext.o \
./libavfilter/vf_fade.o \
./libavfilter/vf_fieldorder.o \
./libavfilter/vf_fifo.o \
./libavfilter/vf_format.o \
./libavfilter/vf_fps.o \
./libavfilter/vf_frei0r.o \
./libavfilter/vf_gradfun.o \
./libavfilter/vf_hflip.o \
./libavfilter/vf_hqdn3d.o \
./libavfilter/vf_idet.o \
./libavfilter/vf_libopencv.o \
./libavfilter/vf_lut.o \
./libavfilter/vf_mp.o \
./libavfilter/vf_null.o \
./libavfilter/vf_overlay.o \
./libavfilter/vf_pad.o \
./libavfilter/vf_pixdesctest.o \
./libavfilter/vf_removelogo.o \
./libavfilter/vf_scale.o \
./libavfilter/vf_select.o \
./libavfilter/vf_setfield.o \
./libavfilter/vf_setpts.o \
./libavfilter/vf_settb.o \
./libavfilter/vf_showinfo.o \
./libavfilter/vf_slicify.o \
./libavfilter/vf_super2xsai.o \
./libavfilter/vf_swapuv.o \
./libavfilter/vf_thumbnail.o \
./libavfilter/vf_tile.o \
./libavfilter/vf_tinterlace.o \
./libavfilter/vf_transpose.o \
./libavfilter/vf_unsharp.o \
./libavfilter/vf_vflip.o \
./libavfilter/vf_yadif.o \
./libavfilter/video.o \
./libavfilter/vsink_nullsink.o \
./libavfilter/vsrc_cellauto.o \
./libavfilter/vsrc_color.o \
./libavfilter/vsrc_life.o \
./libavfilter/vsrc_mandelbrot.o \
./libavfilter/vsrc_mptestsrc.o \
./libavfilter/vsrc_testsrc.o 

C_DEPS += \
./libavfilter/af_aconvert.d \
./libavfilter/af_aformat.d \
./libavfilter/af_amerge.d \
./libavfilter/af_amix.d \
./libavfilter/af_anull.d \
./libavfilter/af_aresample.d \
./libavfilter/af_ashowinfo.d \
./libavfilter/af_astreamsync.d \
./libavfilter/af_asyncts.d \
./libavfilter/af_earwax.d \
./libavfilter/af_pan.d \
./libavfilter/af_resample.d \
./libavfilter/af_silencedetect.d \
./libavfilter/af_volume.d \
./libavfilter/allfilters.d \
./libavfilter/asink_anullsink.d \
./libavfilter/asrc_aevalsrc.d \
./libavfilter/asrc_anullsrc.d \
./libavfilter/audio.d \
./libavfilter/avcodec.d \
./libavfilter/avfilter.d \
./libavfilter/avfiltergraph.d \
./libavfilter/bbox.d \
./libavfilter/buffer.d \
./libavfilter/buffersink.d \
./libavfilter/buffersrc.d \
./libavfilter/defaults.d \
./libavfilter/drawutils.d \
./libavfilter/formats.d \
./libavfilter/graphdump.d \
./libavfilter/graphparser.d \
./libavfilter/lavfutils.d \
./libavfilter/lswsutils.d \
./libavfilter/sink_buffer.d \
./libavfilter/split.d \
./libavfilter/src_buffer.d \
./libavfilter/src_movie.d \
./libavfilter/transform.d \
./libavfilter/vf_aspect.d \
./libavfilter/vf_ass.d \
./libavfilter/vf_bbox.d \
./libavfilter/vf_blackdetect.d \
./libavfilter/vf_blackframe.d \
./libavfilter/vf_boxblur.d \
./libavfilter/vf_colormatrix.d \
./libavfilter/vf_copy.d \
./libavfilter/vf_crop.d \
./libavfilter/vf_cropdetect.d \
./libavfilter/vf_delogo.d \
./libavfilter/vf_deshake.d \
./libavfilter/vf_drawbox.d \
./libavfilter/vf_drawtext.d \
./libavfilter/vf_fade.d \
./libavfilter/vf_fieldorder.d \
./libavfilter/vf_fifo.d \
./libavfilter/vf_format.d \
./libavfilter/vf_fps.d \
./libavfilter/vf_frei0r.d \
./libavfilter/vf_gradfun.d \
./libavfilter/vf_hflip.d \
./libavfilter/vf_hqdn3d.d \
./libavfilter/vf_idet.d \
./libavfilter/vf_libopencv.d \
./libavfilter/vf_lut.d \
./libavfilter/vf_mp.d \
./libavfilter/vf_null.d \
./libavfilter/vf_overlay.d \
./libavfilter/vf_pad.d \
./libavfilter/vf_pixdesctest.d \
./libavfilter/vf_removelogo.d \
./libavfilter/vf_scale.d \
./libavfilter/vf_select.d \
./libavfilter/vf_setfield.d \
./libavfilter/vf_setpts.d \
./libavfilter/vf_settb.d \
./libavfilter/vf_showinfo.d \
./libavfilter/vf_slicify.d \
./libavfilter/vf_super2xsai.d \
./libavfilter/vf_swapuv.d \
./libavfilter/vf_thumbnail.d \
./libavfilter/vf_tile.d \
./libavfilter/vf_tinterlace.d \
./libavfilter/vf_transpose.d \
./libavfilter/vf_unsharp.d \
./libavfilter/vf_vflip.d \
./libavfilter/vf_yadif.d \
./libavfilter/video.d \
./libavfilter/vsink_nullsink.d \
./libavfilter/vsrc_cellauto.d \
./libavfilter/vsrc_color.d \
./libavfilter/vsrc_life.d \
./libavfilter/vsrc_mandelbrot.d \
./libavfilter/vsrc_mptestsrc.d \
./libavfilter/vsrc_testsrc.d 


# Each subdirectory must supply rules for building sources it contributes
libavfilter/%.o: ../libavfilter/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


