################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../libavformat/4xm.o \
../libavformat/a64.o \
../libavformat/aacdec.o \
../libavformat/ac3dec.o \
../libavformat/act.o \
../libavformat/adtsenc.o \
../libavformat/adxdec.o \
../libavformat/aea.o \
../libavformat/aiffdec.o \
../libavformat/aiffenc.o \
../libavformat/allformats.o \
../libavformat/amr.o \
../libavformat/anm.o \
../libavformat/apc.o \
../libavformat/ape.o \
../libavformat/apetag.o \
../libavformat/asf.o \
../libavformat/asfcrypt.o \
../libavformat/asfdec.o \
../libavformat/asfenc.o \
../libavformat/assdec.o \
../libavformat/assenc.o \
../libavformat/au.o \
../libavformat/audiointerleave.o \
../libavformat/avc.o \
../libavformat/avidec.o \
../libavformat/avienc.o \
../libavformat/avio.o \
../libavformat/aviobuf.o \
../libavformat/avlanguage.o \
../libavformat/avs.o \
../libavformat/bethsoftvid.o \
../libavformat/bfi.o \
../libavformat/bink.o \
../libavformat/bintext.o \
../libavformat/bit.o \
../libavformat/bmv.o \
../libavformat/c93.o \
../libavformat/cache.o \
../libavformat/caf.o \
../libavformat/cafdec.o \
../libavformat/cafenc.o \
../libavformat/cavsvideodec.o \
../libavformat/cdg.o \
../libavformat/cdxl.o \
../libavformat/concat.o \
../libavformat/crcenc.o \
../libavformat/crypto.o \
../libavformat/cutils.o \
../libavformat/daud.o \
../libavformat/dfa.o \
../libavformat/diracdec.o \
../libavformat/dnxhddec.o \
../libavformat/dsicin.o \
../libavformat/dtsdec.o \
../libavformat/dv.o \
../libavformat/dvenc.o \
../libavformat/dxa.o \
../libavformat/eacdata.o \
../libavformat/electronicarts.o \
../libavformat/ffmdec.o \
../libavformat/ffmenc.o \
../libavformat/ffmetadec.o \
../libavformat/ffmetaenc.o \
../libavformat/file.o \
../libavformat/filmstripdec.o \
../libavformat/filmstripenc.o \
../libavformat/flacdec.o \
../libavformat/flacenc.o \
../libavformat/flacenc_header.o \
../libavformat/flic.o \
../libavformat/flvdec.o \
../libavformat/flvenc.o \
../libavformat/framecrcenc.o \
../libavformat/framehash.o \
../libavformat/g723_1.o \
../libavformat/g729dec.o \
../libavformat/gif.o \
../libavformat/gopher.o \
../libavformat/gsmdec.o \
../libavformat/gxf.o \
../libavformat/gxfenc.o \
../libavformat/h261dec.o \
../libavformat/h263dec.o \
../libavformat/h264dec.o \
../libavformat/hls.o \
../libavformat/hlsproto.o \
../libavformat/http.o \
../libavformat/httpauth.o \
../libavformat/icodec.o \
../libavformat/id3v1.o \
../libavformat/id3v2.o \
../libavformat/id3v2enc.o \
../libavformat/idcin.o \
../libavformat/idroqdec.o \
../libavformat/idroqenc.o \
../libavformat/iff.o \
../libavformat/img2.o \
../libavformat/img2dec.o \
../libavformat/img2enc.o \
../libavformat/ingenientdec.o \
../libavformat/ipmovie.o \
../libavformat/isom.o \
../libavformat/iss.o \
../libavformat/iv8.o \
../libavformat/ivfdec.o \
../libavformat/ivfenc.o \
../libavformat/jacosubdec.o \
../libavformat/jacosubenc.o \
../libavformat/jvdec.o \
../libavformat/latmenc.o \
../libavformat/librtmp.o \
../libavformat/lmlm4.o \
../libavformat/loasdec.o \
../libavformat/lxfdec.o \
../libavformat/m4vdec.o \
../libavformat/matroska.o \
../libavformat/matroskadec.o \
../libavformat/matroskaenc.o \
../libavformat/md5enc.o \
../libavformat/md5proto.o \
../libavformat/metadata.o \
../libavformat/mgsts.o \
../libavformat/microdvddec.o \
../libavformat/microdvdenc.o \
../libavformat/mkvtimestamp_v2.o \
../libavformat/mm.o \
../libavformat/mmf.o \
../libavformat/mms.o \
../libavformat/mmsh.o \
../libavformat/mmst.o \
../libavformat/mov.o \
../libavformat/mov_chan.o \
../libavformat/movenc.o \
../libavformat/movenchint.o \
../libavformat/mp3dec.o \
../libavformat/mp3enc.o \
../libavformat/mpc.o \
../libavformat/mpc8.o \
../libavformat/mpeg.o \
../libavformat/mpegenc.o \
../libavformat/mpegts.o \
../libavformat/mpegtsenc.o \
../libavformat/mpegvideodec.o \
../libavformat/mpjpeg.o \
../libavformat/msnwc_tcp.o \
../libavformat/mtv.o \
../libavformat/mvi.o \
../libavformat/mxf.o \
../libavformat/mxfdec.o \
../libavformat/mxfenc.o \
../libavformat/mxg.o \
../libavformat/ncdec.o \
../libavformat/network.o \
../libavformat/nsvdec.o \
../libavformat/nullenc.o \
../libavformat/nut.o \
../libavformat/nutdec.o \
../libavformat/nutenc.o \
../libavformat/nuv.o \
../libavformat/oggdec.o \
../libavformat/oggenc.o \
../libavformat/oggparsecelt.o \
../libavformat/oggparsedirac.o \
../libavformat/oggparseflac.o \
../libavformat/oggparseogm.o \
../libavformat/oggparseskeleton.o \
../libavformat/oggparsespeex.o \
../libavformat/oggparsetheora.o \
../libavformat/oggparsevorbis.o \
../libavformat/oma.o \
../libavformat/omadec.o \
../libavformat/omaenc.o \
../libavformat/options.o \
../libavformat/os_support.o \
../libavformat/pcm.o \
../libavformat/pcmdec.o \
../libavformat/pcmenc.o \
../libavformat/pmpdec.o \
../libavformat/psxstr.o \
../libavformat/pva.o \
../libavformat/qcp.o \
../libavformat/r3d.o \
../libavformat/rawdec.o \
../libavformat/rawenc.o \
../libavformat/rawvideodec.o \
../libavformat/rdt.o \
../libavformat/riff.o \
../libavformat/rl2.o \
../libavformat/rm.o \
../libavformat/rmdec.o \
../libavformat/rmenc.o \
../libavformat/rpl.o \
../libavformat/rso.o \
../libavformat/rsodec.o \
../libavformat/rsoenc.o \
../libavformat/rtp.o \
../libavformat/rtpdec.o \
../libavformat/rtpdec_amr.o \
../libavformat/rtpdec_asf.o \
../libavformat/rtpdec_g726.o \
../libavformat/rtpdec_h263.o \
../libavformat/rtpdec_h263_rfc2190.o \
../libavformat/rtpdec_h264.o \
../libavformat/rtpdec_latm.o \
../libavformat/rtpdec_mpeg4.o \
../libavformat/rtpdec_qcelp.o \
../libavformat/rtpdec_qdm2.o \
../libavformat/rtpdec_qt.o \
../libavformat/rtpdec_svq3.o \
../libavformat/rtpdec_vp8.o \
../libavformat/rtpdec_xiph.o \
../libavformat/rtpenc.o \
../libavformat/rtpenc_aac.o \
../libavformat/rtpenc_amr.o \
../libavformat/rtpenc_chain.o \
../libavformat/rtpenc_h263.o \
../libavformat/rtpenc_h263_rfc2190.o \
../libavformat/rtpenc_h264.o \
../libavformat/rtpenc_latm.o \
../libavformat/rtpenc_mpv.o \
../libavformat/rtpenc_vp8.o \
../libavformat/rtpenc_xiph.o \
../libavformat/rtpproto.o \
../libavformat/rtsp.o \
../libavformat/rtspdec.o \
../libavformat/rtspenc.o \
../libavformat/sapdec.o \
../libavformat/sapenc.o \
../libavformat/sauce.o \
../libavformat/sbgdec.o \
../libavformat/sdp.o \
../libavformat/seek.o \
../libavformat/segafilm.o \
../libavformat/segment.o \
../libavformat/sierravmd.o \
../libavformat/siff.o \
../libavformat/smacker.o \
../libavformat/smjpeg.o \
../libavformat/smjpegdec.o \
../libavformat/smjpegenc.o \
../libavformat/sol.o \
../libavformat/soxdec.o \
../libavformat/soxenc.o \
../libavformat/spdif.o \
../libavformat/spdifdec.o \
../libavformat/spdifenc.o \
../libavformat/srtdec.o \
../libavformat/swfdec.o \
../libavformat/swfenc.o \
../libavformat/tcp.o \
../libavformat/thp.o \
../libavformat/tiertexseq.o \
../libavformat/tmv.o \
../libavformat/tta.o \
../libavformat/tty.o \
../libavformat/txd.o \
../libavformat/udp.o \
../libavformat/utils.o \
../libavformat/vc1test.o \
../libavformat/vc1testenc.o \
../libavformat/voc.o \
../libavformat/vocdec.o \
../libavformat/vocenc.o \
../libavformat/vorbiscomment.o \
../libavformat/vqf.o \
../libavformat/wav.o \
../libavformat/wc3movie.o \
../libavformat/westwood_aud.o \
../libavformat/westwood_vqa.o \
../libavformat/wtv.o \
../libavformat/wtvdec.o \
../libavformat/wtvenc.o \
../libavformat/wv.o \
../libavformat/xa.o \
../libavformat/xmv.o \
../libavformat/xwma.o \
../libavformat/yop.o \
../libavformat/yuv4mpeg.o 

C_SRCS += \
../libavformat/4xm.c \
../libavformat/a64.c \
../libavformat/aacdec.c \
../libavformat/ac3dec.c \
../libavformat/act.c \
../libavformat/adtsenc.c \
../libavformat/adxdec.c \
../libavformat/aea.c \
../libavformat/aiffdec.c \
../libavformat/aiffenc.c \
../libavformat/allformats.c \
../libavformat/amr.c \
../libavformat/anm.c \
../libavformat/apc.c \
../libavformat/ape.c \
../libavformat/apetag.c \
../libavformat/asf.c \
../libavformat/asfcrypt.c \
../libavformat/asfdec.c \
../libavformat/asfenc.c \
../libavformat/assdec.c \
../libavformat/assenc.c \
../libavformat/au.c \
../libavformat/audiointerleave.c \
../libavformat/avc.c \
../libavformat/avidec.c \
../libavformat/avienc.c \
../libavformat/avio.c \
../libavformat/aviobuf.c \
../libavformat/avisynth.c \
../libavformat/avlanguage.c \
../libavformat/avs.c \
../libavformat/bethsoftvid.c \
../libavformat/bfi.c \
../libavformat/bink.c \
../libavformat/bintext.c \
../libavformat/bit.c \
../libavformat/bluray.c \
../libavformat/bmv.c \
../libavformat/c93.c \
../libavformat/cache.c \
../libavformat/caf.c \
../libavformat/cafdec.c \
../libavformat/cafenc.c \
../libavformat/cavsvideodec.c \
../libavformat/cdg.c \
../libavformat/cdxl.c \
../libavformat/concat.c \
../libavformat/crcenc.c \
../libavformat/crypto.c \
../libavformat/cutils.c \
../libavformat/daud.c \
../libavformat/dfa.c \
../libavformat/diracdec.c \
../libavformat/dnxhddec.c \
../libavformat/dsicin.c \
../libavformat/dtsdec.c \
../libavformat/dv.c \
../libavformat/dvenc.c \
../libavformat/dxa.c \
../libavformat/eacdata.c \
../libavformat/electronicarts.c \
../libavformat/ffmdec.c \
../libavformat/ffmenc.c \
../libavformat/ffmetadec.c \
../libavformat/ffmetaenc.c \
../libavformat/file.c \
../libavformat/filmstripdec.c \
../libavformat/filmstripenc.c \
../libavformat/flacdec.c \
../libavformat/flacenc.c \
../libavformat/flacenc_header.c \
../libavformat/flic.c \
../libavformat/flvdec.c \
../libavformat/flvenc.c \
../libavformat/framecrcenc.c \
../libavformat/framehash.c \
../libavformat/g723_1.c \
../libavformat/g729dec.c \
../libavformat/gif.c \
../libavformat/gopher.c \
../libavformat/gsmdec.c \
../libavformat/gxf.c \
../libavformat/gxfenc.c \
../libavformat/h261dec.c \
../libavformat/h263dec.c \
../libavformat/h264dec.c \
../libavformat/hls.c \
../libavformat/hlsproto.c \
../libavformat/http.c \
../libavformat/httpauth.c \
../libavformat/icodec.c \
../libavformat/id3v1.c \
../libavformat/id3v2.c \
../libavformat/id3v2enc.c \
../libavformat/idcin.c \
../libavformat/idroqdec.c \
../libavformat/idroqenc.c \
../libavformat/iff.c \
../libavformat/img2.c \
../libavformat/img2dec.c \
../libavformat/img2enc.c \
../libavformat/ingenientdec.c \
../libavformat/ipmovie.c \
../libavformat/isom.c \
../libavformat/iss.c \
../libavformat/iv8.c \
../libavformat/ivfdec.c \
../libavformat/ivfenc.c \
../libavformat/jacosubdec.c \
../libavformat/jacosubenc.c \
../libavformat/jvdec.c \
../libavformat/latmenc.c \
../libavformat/libmodplug.c \
../libavformat/libnut.c \
../libavformat/librtmp.c \
../libavformat/lmlm4.c \
../libavformat/loasdec.c \
../libavformat/lxfdec.c \
../libavformat/m4vdec.c \
../libavformat/matroska.c \
../libavformat/matroskadec.c \
../libavformat/matroskaenc.c \
../libavformat/md5enc.c \
../libavformat/md5proto.c \
../libavformat/metadata.c \
../libavformat/mgsts.c \
../libavformat/microdvddec.c \
../libavformat/microdvdenc.c \
../libavformat/mkvtimestamp_v2.c \
../libavformat/mm.c \
../libavformat/mmf.c \
../libavformat/mms.c \
../libavformat/mmsh.c \
../libavformat/mmst.c \
../libavformat/mov.c \
../libavformat/mov_chan.c \
../libavformat/movenc.c \
../libavformat/movenchint.c \
../libavformat/mp3dec.c \
../libavformat/mp3enc.c \
../libavformat/mpc.c \
../libavformat/mpc8.c \
../libavformat/mpeg.c \
../libavformat/mpegenc.c \
../libavformat/mpegts.c \
../libavformat/mpegtsenc.c \
../libavformat/mpegvideodec.c \
../libavformat/mpjpeg.c \
../libavformat/msnwc_tcp.c \
../libavformat/mtv.c \
../libavformat/mvi.c \
../libavformat/mxf.c \
../libavformat/mxfdec.c \
../libavformat/mxfenc.c \
../libavformat/mxg.c \
../libavformat/ncdec.c \
../libavformat/network.c \
../libavformat/nsvdec.c \
../libavformat/nullenc.c \
../libavformat/nut.c \
../libavformat/nutdec.c \
../libavformat/nutenc.c \
../libavformat/nuv.c \
../libavformat/oggdec.c \
../libavformat/oggenc.c \
../libavformat/oggparsecelt.c \
../libavformat/oggparsedirac.c \
../libavformat/oggparseflac.c \
../libavformat/oggparseogm.c \
../libavformat/oggparseskeleton.c \
../libavformat/oggparsespeex.c \
../libavformat/oggparsetheora.c \
../libavformat/oggparsevorbis.c \
../libavformat/oma.c \
../libavformat/omadec.c \
../libavformat/omaenc.c \
../libavformat/options.c \
../libavformat/os_support.c \
../libavformat/pcm.c \
../libavformat/pcmdec.c \
../libavformat/pcmenc.c \
../libavformat/pmpdec.c \
../libavformat/psxstr.c \
../libavformat/pva.c \
../libavformat/qcp.c \
../libavformat/r3d.c \
../libavformat/rawdec.c \
../libavformat/rawenc.c \
../libavformat/rawvideodec.c \
../libavformat/rdt.c \
../libavformat/riff.c \
../libavformat/rl2.c \
../libavformat/rm.c \
../libavformat/rmdec.c \
../libavformat/rmenc.c \
../libavformat/rpl.c \
../libavformat/rso.c \
../libavformat/rsodec.c \
../libavformat/rsoenc.c \
../libavformat/rtmppkt.c \
../libavformat/rtmpproto.c \
../libavformat/rtp.c \
../libavformat/rtpdec.c \
../libavformat/rtpdec_amr.c \
../libavformat/rtpdec_asf.c \
../libavformat/rtpdec_g726.c \
../libavformat/rtpdec_h263.c \
../libavformat/rtpdec_h263_rfc2190.c \
../libavformat/rtpdec_h264.c \
../libavformat/rtpdec_latm.c \
../libavformat/rtpdec_mpeg4.c \
../libavformat/rtpdec_qcelp.c \
../libavformat/rtpdec_qdm2.c \
../libavformat/rtpdec_qt.c \
../libavformat/rtpdec_svq3.c \
../libavformat/rtpdec_vp8.c \
../libavformat/rtpdec_xiph.c \
../libavformat/rtpenc.c \
../libavformat/rtpenc_aac.c \
../libavformat/rtpenc_amr.c \
../libavformat/rtpenc_chain.c \
../libavformat/rtpenc_h263.c \
../libavformat/rtpenc_h263_rfc2190.c \
../libavformat/rtpenc_h264.c \
../libavformat/rtpenc_latm.c \
../libavformat/rtpenc_mpv.c \
../libavformat/rtpenc_vp8.c \
../libavformat/rtpenc_xiph.c \
../libavformat/rtpproto.c \
../libavformat/rtsp.c \
../libavformat/rtspdec.c \
../libavformat/rtspenc.c \
../libavformat/sapdec.c \
../libavformat/sapenc.c \
../libavformat/sauce.c \
../libavformat/sbgdec.c \
../libavformat/sctp.c \
../libavformat/sdp.c \
../libavformat/seek-test.c \
../libavformat/seek.c \
../libavformat/segafilm.c \
../libavformat/segment.c \
../libavformat/sierravmd.c \
../libavformat/siff.c \
../libavformat/smacker.c \
../libavformat/smjpeg.c \
../libavformat/smjpegdec.c \
../libavformat/smjpegenc.c \
../libavformat/sol.c \
../libavformat/soxdec.c \
../libavformat/soxenc.c \
../libavformat/spdif.c \
../libavformat/spdifdec.c \
../libavformat/spdifenc.c \
../libavformat/srtdec.c \
../libavformat/swfdec.c \
../libavformat/swfenc.c \
../libavformat/tcp.c \
../libavformat/thp.c \
../libavformat/tiertexseq.c \
../libavformat/tls.c \
../libavformat/tmv.c \
../libavformat/tta.c \
../libavformat/tty.c \
../libavformat/txd.c \
../libavformat/udp.c \
../libavformat/utils.c \
../libavformat/vc1test.c \
../libavformat/vc1testenc.c \
../libavformat/voc.c \
../libavformat/vocdec.c \
../libavformat/vocenc.c \
../libavformat/vorbiscomment.c \
../libavformat/vqf.c \
../libavformat/wav.c \
../libavformat/wc3movie.c \
../libavformat/westwood_aud.c \
../libavformat/westwood_vqa.c \
../libavformat/wtv.c \
../libavformat/wtvdec.c \
../libavformat/wtvenc.c \
../libavformat/wv.c \
../libavformat/xa.c \
../libavformat/xmv.c \
../libavformat/xwma.c \
../libavformat/yop.c \
../libavformat/yuv4mpeg.c 

OBJS += \
./libavformat/4xm.o \
./libavformat/a64.o \
./libavformat/aacdec.o \
./libavformat/ac3dec.o \
./libavformat/act.o \
./libavformat/adtsenc.o \
./libavformat/adxdec.o \
./libavformat/aea.o \
./libavformat/aiffdec.o \
./libavformat/aiffenc.o \
./libavformat/allformats.o \
./libavformat/amr.o \
./libavformat/anm.o \
./libavformat/apc.o \
./libavformat/ape.o \
./libavformat/apetag.o \
./libavformat/asf.o \
./libavformat/asfcrypt.o \
./libavformat/asfdec.o \
./libavformat/asfenc.o \
./libavformat/assdec.o \
./libavformat/assenc.o \
./libavformat/au.o \
./libavformat/audiointerleave.o \
./libavformat/avc.o \
./libavformat/avidec.o \
./libavformat/avienc.o \
./libavformat/avio.o \
./libavformat/aviobuf.o \
./libavformat/avisynth.o \
./libavformat/avlanguage.o \
./libavformat/avs.o \
./libavformat/bethsoftvid.o \
./libavformat/bfi.o \
./libavformat/bink.o \
./libavformat/bintext.o \
./libavformat/bit.o \
./libavformat/bluray.o \
./libavformat/bmv.o \
./libavformat/c93.o \
./libavformat/cache.o \
./libavformat/caf.o \
./libavformat/cafdec.o \
./libavformat/cafenc.o \
./libavformat/cavsvideodec.o \
./libavformat/cdg.o \
./libavformat/cdxl.o \
./libavformat/concat.o \
./libavformat/crcenc.o \
./libavformat/crypto.o \
./libavformat/cutils.o \
./libavformat/daud.o \
./libavformat/dfa.o \
./libavformat/diracdec.o \
./libavformat/dnxhddec.o \
./libavformat/dsicin.o \
./libavformat/dtsdec.o \
./libavformat/dv.o \
./libavformat/dvenc.o \
./libavformat/dxa.o \
./libavformat/eacdata.o \
./libavformat/electronicarts.o \
./libavformat/ffmdec.o \
./libavformat/ffmenc.o \
./libavformat/ffmetadec.o \
./libavformat/ffmetaenc.o \
./libavformat/file.o \
./libavformat/filmstripdec.o \
./libavformat/filmstripenc.o \
./libavformat/flacdec.o \
./libavformat/flacenc.o \
./libavformat/flacenc_header.o \
./libavformat/flic.o \
./libavformat/flvdec.o \
./libavformat/flvenc.o \
./libavformat/framecrcenc.o \
./libavformat/framehash.o \
./libavformat/g723_1.o \
./libavformat/g729dec.o \
./libavformat/gif.o \
./libavformat/gopher.o \
./libavformat/gsmdec.o \
./libavformat/gxf.o \
./libavformat/gxfenc.o \
./libavformat/h261dec.o \
./libavformat/h263dec.o \
./libavformat/h264dec.o \
./libavformat/hls.o \
./libavformat/hlsproto.o \
./libavformat/http.o \
./libavformat/httpauth.o \
./libavformat/icodec.o \
./libavformat/id3v1.o \
./libavformat/id3v2.o \
./libavformat/id3v2enc.o \
./libavformat/idcin.o \
./libavformat/idroqdec.o \
./libavformat/idroqenc.o \
./libavformat/iff.o \
./libavformat/img2.o \
./libavformat/img2dec.o \
./libavformat/img2enc.o \
./libavformat/ingenientdec.o \
./libavformat/ipmovie.o \
./libavformat/isom.o \
./libavformat/iss.o \
./libavformat/iv8.o \
./libavformat/ivfdec.o \
./libavformat/ivfenc.o \
./libavformat/jacosubdec.o \
./libavformat/jacosubenc.o \
./libavformat/jvdec.o \
./libavformat/latmenc.o \
./libavformat/libmodplug.o \
./libavformat/libnut.o \
./libavformat/librtmp.o \
./libavformat/lmlm4.o \
./libavformat/loasdec.o \
./libavformat/lxfdec.o \
./libavformat/m4vdec.o \
./libavformat/matroska.o \
./libavformat/matroskadec.o \
./libavformat/matroskaenc.o \
./libavformat/md5enc.o \
./libavformat/md5proto.o \
./libavformat/metadata.o \
./libavformat/mgsts.o \
./libavformat/microdvddec.o \
./libavformat/microdvdenc.o \
./libavformat/mkvtimestamp_v2.o \
./libavformat/mm.o \
./libavformat/mmf.o \
./libavformat/mms.o \
./libavformat/mmsh.o \
./libavformat/mmst.o \
./libavformat/mov.o \
./libavformat/mov_chan.o \
./libavformat/movenc.o \
./libavformat/movenchint.o \
./libavformat/mp3dec.o \
./libavformat/mp3enc.o \
./libavformat/mpc.o \
./libavformat/mpc8.o \
./libavformat/mpeg.o \
./libavformat/mpegenc.o \
./libavformat/mpegts.o \
./libavformat/mpegtsenc.o \
./libavformat/mpegvideodec.o \
./libavformat/mpjpeg.o \
./libavformat/msnwc_tcp.o \
./libavformat/mtv.o \
./libavformat/mvi.o \
./libavformat/mxf.o \
./libavformat/mxfdec.o \
./libavformat/mxfenc.o \
./libavformat/mxg.o \
./libavformat/ncdec.o \
./libavformat/network.o \
./libavformat/nsvdec.o \
./libavformat/nullenc.o \
./libavformat/nut.o \
./libavformat/nutdec.o \
./libavformat/nutenc.o \
./libavformat/nuv.o \
./libavformat/oggdec.o \
./libavformat/oggenc.o \
./libavformat/oggparsecelt.o \
./libavformat/oggparsedirac.o \
./libavformat/oggparseflac.o \
./libavformat/oggparseogm.o \
./libavformat/oggparseskeleton.o \
./libavformat/oggparsespeex.o \
./libavformat/oggparsetheora.o \
./libavformat/oggparsevorbis.o \
./libavformat/oma.o \
./libavformat/omadec.o \
./libavformat/omaenc.o \
./libavformat/options.o \
./libavformat/os_support.o \
./libavformat/pcm.o \
./libavformat/pcmdec.o \
./libavformat/pcmenc.o \
./libavformat/pmpdec.o \
./libavformat/psxstr.o \
./libavformat/pva.o \
./libavformat/qcp.o \
./libavformat/r3d.o \
./libavformat/rawdec.o \
./libavformat/rawenc.o \
./libavformat/rawvideodec.o \
./libavformat/rdt.o \
./libavformat/riff.o \
./libavformat/rl2.o \
./libavformat/rm.o \
./libavformat/rmdec.o \
./libavformat/rmenc.o \
./libavformat/rpl.o \
./libavformat/rso.o \
./libavformat/rsodec.o \
./libavformat/rsoenc.o \
./libavformat/rtmppkt.o \
./libavformat/rtmpproto.o \
./libavformat/rtp.o \
./libavformat/rtpdec.o \
./libavformat/rtpdec_amr.o \
./libavformat/rtpdec_asf.o \
./libavformat/rtpdec_g726.o \
./libavformat/rtpdec_h263.o \
./libavformat/rtpdec_h263_rfc2190.o \
./libavformat/rtpdec_h264.o \
./libavformat/rtpdec_latm.o \
./libavformat/rtpdec_mpeg4.o \
./libavformat/rtpdec_qcelp.o \
./libavformat/rtpdec_qdm2.o \
./libavformat/rtpdec_qt.o \
./libavformat/rtpdec_svq3.o \
./libavformat/rtpdec_vp8.o \
./libavformat/rtpdec_xiph.o \
./libavformat/rtpenc.o \
./libavformat/rtpenc_aac.o \
./libavformat/rtpenc_amr.o \
./libavformat/rtpenc_chain.o \
./libavformat/rtpenc_h263.o \
./libavformat/rtpenc_h263_rfc2190.o \
./libavformat/rtpenc_h264.o \
./libavformat/rtpenc_latm.o \
./libavformat/rtpenc_mpv.o \
./libavformat/rtpenc_vp8.o \
./libavformat/rtpenc_xiph.o \
./libavformat/rtpproto.o \
./libavformat/rtsp.o \
./libavformat/rtspdec.o \
./libavformat/rtspenc.o \
./libavformat/sapdec.o \
./libavformat/sapenc.o \
./libavformat/sauce.o \
./libavformat/sbgdec.o \
./libavformat/sctp.o \
./libavformat/sdp.o \
./libavformat/seek-test.o \
./libavformat/seek.o \
./libavformat/segafilm.o \
./libavformat/segment.o \
./libavformat/sierravmd.o \
./libavformat/siff.o \
./libavformat/smacker.o \
./libavformat/smjpeg.o \
./libavformat/smjpegdec.o \
./libavformat/smjpegenc.o \
./libavformat/sol.o \
./libavformat/soxdec.o \
./libavformat/soxenc.o \
./libavformat/spdif.o \
./libavformat/spdifdec.o \
./libavformat/spdifenc.o \
./libavformat/srtdec.o \
./libavformat/swfdec.o \
./libavformat/swfenc.o \
./libavformat/tcp.o \
./libavformat/thp.o \
./libavformat/tiertexseq.o \
./libavformat/tls.o \
./libavformat/tmv.o \
./libavformat/tta.o \
./libavformat/tty.o \
./libavformat/txd.o \
./libavformat/udp.o \
./libavformat/utils.o \
./libavformat/vc1test.o \
./libavformat/vc1testenc.o \
./libavformat/voc.o \
./libavformat/vocdec.o \
./libavformat/vocenc.o \
./libavformat/vorbiscomment.o \
./libavformat/vqf.o \
./libavformat/wav.o \
./libavformat/wc3movie.o \
./libavformat/westwood_aud.o \
./libavformat/westwood_vqa.o \
./libavformat/wtv.o \
./libavformat/wtvdec.o \
./libavformat/wtvenc.o \
./libavformat/wv.o \
./libavformat/xa.o \
./libavformat/xmv.o \
./libavformat/xwma.o \
./libavformat/yop.o \
./libavformat/yuv4mpeg.o 

C_DEPS += \
./libavformat/4xm.d \
./libavformat/a64.d \
./libavformat/aacdec.d \
./libavformat/ac3dec.d \
./libavformat/act.d \
./libavformat/adtsenc.d \
./libavformat/adxdec.d \
./libavformat/aea.d \
./libavformat/aiffdec.d \
./libavformat/aiffenc.d \
./libavformat/allformats.d \
./libavformat/amr.d \
./libavformat/anm.d \
./libavformat/apc.d \
./libavformat/ape.d \
./libavformat/apetag.d \
./libavformat/asf.d \
./libavformat/asfcrypt.d \
./libavformat/asfdec.d \
./libavformat/asfenc.d \
./libavformat/assdec.d \
./libavformat/assenc.d \
./libavformat/au.d \
./libavformat/audiointerleave.d \
./libavformat/avc.d \
./libavformat/avidec.d \
./libavformat/avienc.d \
./libavformat/avio.d \
./libavformat/aviobuf.d \
./libavformat/avisynth.d \
./libavformat/avlanguage.d \
./libavformat/avs.d \
./libavformat/bethsoftvid.d \
./libavformat/bfi.d \
./libavformat/bink.d \
./libavformat/bintext.d \
./libavformat/bit.d \
./libavformat/bluray.d \
./libavformat/bmv.d \
./libavformat/c93.d \
./libavformat/cache.d \
./libavformat/caf.d \
./libavformat/cafdec.d \
./libavformat/cafenc.d \
./libavformat/cavsvideodec.d \
./libavformat/cdg.d \
./libavformat/cdxl.d \
./libavformat/concat.d \
./libavformat/crcenc.d \
./libavformat/crypto.d \
./libavformat/cutils.d \
./libavformat/daud.d \
./libavformat/dfa.d \
./libavformat/diracdec.d \
./libavformat/dnxhddec.d \
./libavformat/dsicin.d \
./libavformat/dtsdec.d \
./libavformat/dv.d \
./libavformat/dvenc.d \
./libavformat/dxa.d \
./libavformat/eacdata.d \
./libavformat/electronicarts.d \
./libavformat/ffmdec.d \
./libavformat/ffmenc.d \
./libavformat/ffmetadec.d \
./libavformat/ffmetaenc.d \
./libavformat/file.d \
./libavformat/filmstripdec.d \
./libavformat/filmstripenc.d \
./libavformat/flacdec.d \
./libavformat/flacenc.d \
./libavformat/flacenc_header.d \
./libavformat/flic.d \
./libavformat/flvdec.d \
./libavformat/flvenc.d \
./libavformat/framecrcenc.d \
./libavformat/framehash.d \
./libavformat/g723_1.d \
./libavformat/g729dec.d \
./libavformat/gif.d \
./libavformat/gopher.d \
./libavformat/gsmdec.d \
./libavformat/gxf.d \
./libavformat/gxfenc.d \
./libavformat/h261dec.d \
./libavformat/h263dec.d \
./libavformat/h264dec.d \
./libavformat/hls.d \
./libavformat/hlsproto.d \
./libavformat/http.d \
./libavformat/httpauth.d \
./libavformat/icodec.d \
./libavformat/id3v1.d \
./libavformat/id3v2.d \
./libavformat/id3v2enc.d \
./libavformat/idcin.d \
./libavformat/idroqdec.d \
./libavformat/idroqenc.d \
./libavformat/iff.d \
./libavformat/img2.d \
./libavformat/img2dec.d \
./libavformat/img2enc.d \
./libavformat/ingenientdec.d \
./libavformat/ipmovie.d \
./libavformat/isom.d \
./libavformat/iss.d \
./libavformat/iv8.d \
./libavformat/ivfdec.d \
./libavformat/ivfenc.d \
./libavformat/jacosubdec.d \
./libavformat/jacosubenc.d \
./libavformat/jvdec.d \
./libavformat/latmenc.d \
./libavformat/libmodplug.d \
./libavformat/libnut.d \
./libavformat/librtmp.d \
./libavformat/lmlm4.d \
./libavformat/loasdec.d \
./libavformat/lxfdec.d \
./libavformat/m4vdec.d \
./libavformat/matroska.d \
./libavformat/matroskadec.d \
./libavformat/matroskaenc.d \
./libavformat/md5enc.d \
./libavformat/md5proto.d \
./libavformat/metadata.d \
./libavformat/mgsts.d \
./libavformat/microdvddec.d \
./libavformat/microdvdenc.d \
./libavformat/mkvtimestamp_v2.d \
./libavformat/mm.d \
./libavformat/mmf.d \
./libavformat/mms.d \
./libavformat/mmsh.d \
./libavformat/mmst.d \
./libavformat/mov.d \
./libavformat/mov_chan.d \
./libavformat/movenc.d \
./libavformat/movenchint.d \
./libavformat/mp3dec.d \
./libavformat/mp3enc.d \
./libavformat/mpc.d \
./libavformat/mpc8.d \
./libavformat/mpeg.d \
./libavformat/mpegenc.d \
./libavformat/mpegts.d \
./libavformat/mpegtsenc.d \
./libavformat/mpegvideodec.d \
./libavformat/mpjpeg.d \
./libavformat/msnwc_tcp.d \
./libavformat/mtv.d \
./libavformat/mvi.d \
./libavformat/mxf.d \
./libavformat/mxfdec.d \
./libavformat/mxfenc.d \
./libavformat/mxg.d \
./libavformat/ncdec.d \
./libavformat/network.d \
./libavformat/nsvdec.d \
./libavformat/nullenc.d \
./libavformat/nut.d \
./libavformat/nutdec.d \
./libavformat/nutenc.d \
./libavformat/nuv.d \
./libavformat/oggdec.d \
./libavformat/oggenc.d \
./libavformat/oggparsecelt.d \
./libavformat/oggparsedirac.d \
./libavformat/oggparseflac.d \
./libavformat/oggparseogm.d \
./libavformat/oggparseskeleton.d \
./libavformat/oggparsespeex.d \
./libavformat/oggparsetheora.d \
./libavformat/oggparsevorbis.d \
./libavformat/oma.d \
./libavformat/omadec.d \
./libavformat/omaenc.d \
./libavformat/options.d \
./libavformat/os_support.d \
./libavformat/pcm.d \
./libavformat/pcmdec.d \
./libavformat/pcmenc.d \
./libavformat/pmpdec.d \
./libavformat/psxstr.d \
./libavformat/pva.d \
./libavformat/qcp.d \
./libavformat/r3d.d \
./libavformat/rawdec.d \
./libavformat/rawenc.d \
./libavformat/rawvideodec.d \
./libavformat/rdt.d \
./libavformat/riff.d \
./libavformat/rl2.d \
./libavformat/rm.d \
./libavformat/rmdec.d \
./libavformat/rmenc.d \
./libavformat/rpl.d \
./libavformat/rso.d \
./libavformat/rsodec.d \
./libavformat/rsoenc.d \
./libavformat/rtmppkt.d \
./libavformat/rtmpproto.d \
./libavformat/rtp.d \
./libavformat/rtpdec.d \
./libavformat/rtpdec_amr.d \
./libavformat/rtpdec_asf.d \
./libavformat/rtpdec_g726.d \
./libavformat/rtpdec_h263.d \
./libavformat/rtpdec_h263_rfc2190.d \
./libavformat/rtpdec_h264.d \
./libavformat/rtpdec_latm.d \
./libavformat/rtpdec_mpeg4.d \
./libavformat/rtpdec_qcelp.d \
./libavformat/rtpdec_qdm2.d \
./libavformat/rtpdec_qt.d \
./libavformat/rtpdec_svq3.d \
./libavformat/rtpdec_vp8.d \
./libavformat/rtpdec_xiph.d \
./libavformat/rtpenc.d \
./libavformat/rtpenc_aac.d \
./libavformat/rtpenc_amr.d \
./libavformat/rtpenc_chain.d \
./libavformat/rtpenc_h263.d \
./libavformat/rtpenc_h263_rfc2190.d \
./libavformat/rtpenc_h264.d \
./libavformat/rtpenc_latm.d \
./libavformat/rtpenc_mpv.d \
./libavformat/rtpenc_vp8.d \
./libavformat/rtpenc_xiph.d \
./libavformat/rtpproto.d \
./libavformat/rtsp.d \
./libavformat/rtspdec.d \
./libavformat/rtspenc.d \
./libavformat/sapdec.d \
./libavformat/sapenc.d \
./libavformat/sauce.d \
./libavformat/sbgdec.d \
./libavformat/sctp.d \
./libavformat/sdp.d \
./libavformat/seek-test.d \
./libavformat/seek.d \
./libavformat/segafilm.d \
./libavformat/segment.d \
./libavformat/sierravmd.d \
./libavformat/siff.d \
./libavformat/smacker.d \
./libavformat/smjpeg.d \
./libavformat/smjpegdec.d \
./libavformat/smjpegenc.d \
./libavformat/sol.d \
./libavformat/soxdec.d \
./libavformat/soxenc.d \
./libavformat/spdif.d \
./libavformat/spdifdec.d \
./libavformat/spdifenc.d \
./libavformat/srtdec.d \
./libavformat/swfdec.d \
./libavformat/swfenc.d \
./libavformat/tcp.d \
./libavformat/thp.d \
./libavformat/tiertexseq.d \
./libavformat/tls.d \
./libavformat/tmv.d \
./libavformat/tta.d \
./libavformat/tty.d \
./libavformat/txd.d \
./libavformat/udp.d \
./libavformat/utils.d \
./libavformat/vc1test.d \
./libavformat/vc1testenc.d \
./libavformat/voc.d \
./libavformat/vocdec.d \
./libavformat/vocenc.d \
./libavformat/vorbiscomment.d \
./libavformat/vqf.d \
./libavformat/wav.d \
./libavformat/wc3movie.d \
./libavformat/westwood_aud.d \
./libavformat/westwood_vqa.d \
./libavformat/wtv.d \
./libavformat/wtvdec.d \
./libavformat/wtvenc.d \
./libavformat/wv.d \
./libavformat/xa.d \
./libavformat/xmv.d \
./libavformat/xwma.d \
./libavformat/yop.d \
./libavformat/yuv4mpeg.d 


# Each subdirectory must supply rules for building sources it contributes
libavformat/%.o: ../libavformat/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


